services:
  database:
    image: "postgres:16"
    container_name: olx-scraper-db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "olx_scraper"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - olx_pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d olx_scraper"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  olx_pg_data:
    driver: local
